import house1 from "../../../assets/images/apartement (2).jpg";
import house2 from "../../../assets/images/apartement (6).jpg";
import house3 from "../../../assets/images/apartement (7).jpg";
import house4 from "../../../assets/images/apartement (8).jpg";
import house5 from "../../../assets/images/apartement (5).jpg";
import house6 from "../../../assets/images/apartement (17).jpg";
import house7 from "../../../assets/images/apartement (5).avif";
import house8 from "../../../assets/images/office.jpg";
import house9 from "../../../assets/images/apartement (16).jpg";
import house10 from "../../../assets/images/apartement (1).jpg";

const data = [
  {
    id: 0,
    image: house1,
    propertyName: "3rd Street House",
    location: "3rd Street, Kart-e-Char",
    city: "Kabul",
    price: "$25,000",
    totalArea: "250 m²",
    bedrooms: 4,
    bathrooms: 3,
    status: "For Sale",
    category: "Residential",
    propertyType: "House",
  },
  {
    id: 1,
    image: house2,
    propertyName: "Modern Villa",
    location: "Shahr-e-Naw",
    city: "Herat",
    price: "$45,000",
    totalArea: "320 m²",
    bedrooms: 5,
    bathrooms: 4,
    status: "For Sale",
    category: "Residential",
    propertyType: "House",
  },
  {
    id: 2,
    image: house3,
    propertyName: "Family Apartment",
    location: "City Center",
    city: "Mazar",
    price: "$18,000",
    totalArea: "180 m²",
    bedrooms: 3,
    bathrooms: 2,
    status: "For Rent",
    category: "Residential",
    propertyType: "Apartment",
  },
  {
    id: 3,
    image: house4,
    propertyName: "Luxury Duplex",
    location: "Main Road",
    city: "Jalalabad",
    price: "$60,000",
    totalArea: "400 m²",
    bedrooms: 6,
    bathrooms: 5,
    status: "For Sale",
    category: "Residential",
    propertyType: "House",
  },
  {
    id: 4,
    image: house5,
    propertyName: "Cozy Townhouse",
    location: "Green Area",
    city: "Kandahar",
    price: "$22,000",
    totalArea: "210 m²",
    bedrooms: 3,
    bathrooms: 2,
    status: "For Rent",
    category: "Residential",
    propertyType: "House",
  },
  {
    id: 5,
    image: house6,
    propertyName: "City View Apartment",
    location: "Macroyan",
    city: "Kabul",
    price: "$30,000",
    totalArea: "200 m²",
    bedrooms: 4,
    bathrooms: 3,
    status: "For Sale",
    category: "Residential",
    propertyType: "Apartment",
  },
  {
    id: 6,
    image: house7,
    propertyName: "Downtown Office",
    location: "Business District",
    city: "Kabul",
    price: "$100,000",
    totalArea: "500 m²",
    bedrooms: 0,
    bathrooms: 2,
    status: "For Sale",
    category: "Commercial",
    propertyType: "Office",
  },
  {
    id: 7,
    image: house8,
    propertyName: "Shopping Complex",
    location: "Main Street",
    city: "Herat",
    price: "$200,000",
    totalArea: "1200 m²",
    bedrooms: 0,
    bathrooms: 8,
    status: "For Sale",
    category: "Commercial",
    propertyType: "Shop",
  },
  {
    id: 8,
    image: house9,
    propertyName: "Warehouse",
    location: "Industrial Zone",
    city: "Kandahar",
    price: "$150,000",
    totalArea: "900 m²",
    bedrooms: 0,
    bathrooms: 3,
    status: "For Rent",
    category: "Commercial",
    propertyType: "Warehouse",
  },
  {
    id: 9,
    image: house10,
    propertyName: "Warehouse",
    location: "Industrial Zone",
    city: "Kandahar",
    price: "$150,000",
    totalArea: "900 m²",
    bedrooms: 0,
    bathrooms: 3,
    status: "For Rent",
    category: "Commercial",
    propertyType: "Warehouse",
  },
];

export default data;
